// create enum of token types like: ACCESS_TOKEN, REFRESH_TOKEN, MEMBER_INVITATION_TOKEN
export enum TokenTypes {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  API_TOKEN = 'API_TOKEN',
  MAGIC_LINK_TOKEN = 'MAGIC_LINK_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  ORGANIZATION_MEMBER_INVITATION_TOKEN = 'ORGANIZATION_MEMBER_INVITATION_TOKEN',
}
